### ISSUE TITLE
start and end?

### ISSUE THREAD

**Issue by tunnckoCore** [jonschlinkert/gfm-code-blocks#1]
cuz I need them, it is easy to implement and cost nothing (instead `eslint-disable-line` in my case, lol)

`````` js
var re = require('gfm-code-block-regex')()

function gfm (str) {
  var arr = []
  var match = null

  while (match = re.exec(str)) { // eslint-disable-line no-cond-assign
    arr.push({
      start: match.index,
      end: match.index + match[1].length,
      lang: match[3],
      code: match[5],
      block: match[1]
    })
  }
  return arr
}
gfm('abc\n```bash\nbar\n```\nxyz')
//=> [ { start: 4,
//    end: 19,
//    lang: 'bash',
//    code: 'bar',
//    block: '```bash\nbar\n```' } ]
``````

**Comment by tunnckoCore** [comment]
Cuz i think to do a PR in `feross/standard` to support linting for javascript code blocks in markdown files with some flag (i.e. `--markdown/--md`).

That will help and will join in game where standard read files synchronously passing file content to the internal check/formatting function then write back to file, so we need positions.

**Comment by tunnckoCore** [comment]
actually, no. it can be implemented without start/end, but that feature would be useful and cost nothing. :100:

**Comment by jonschlinkert** [comment]
so, to summarize you want to do a pr to add `start` and `end` to the object? is that what you're suggesting?

**Comment by tunnckoCore** [comment]
@jonschlinkert yep, which will be as code above

**Comment by jonschlinkert** [comment]
k, sounds good. thanks

**Comment by tunnckoCore** [comment]
closing b/c #2 pr - done
